root: true
env:
  browser: true
  node: true
  es6: true
  es2020: true
  commonjs: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - plugin:vue/base
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier
plugins:
  - vue
  - prettier
  - "@typescript-eslint"
parser: vue-eslint-parser
parserOptions:
  parser: "@typescript-eslint/parser"
  sourceType: module
  allowImportExportEverywhere: true
rules:
  no-console: error
